title: Blog
author: Felipe Marinho
email: felipebmarinho@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I´ll try to post my progress in learning and improving my programming skills.

# social links
twitter_username: felipemarinho # DO NOT include the @ character, or else the build will fail!
github_username:  fbmarinho # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
